# project info
site_name: Obsidian Jira Cloud
site_url: https://pages.nathan-smith.org/obsidian-jira-cloud/
repo_url: https://github.com/OfficerHalf/obsidian-jira-cloud
repo_name: obsidian-jira-cloud
edit_uri: blob/main/doc/docs
site_author: Nathan Smith
copyright: Copyright &copy; 2023 Nathan Smith

# site structure
nav:
  - "index.md"
  - "configuration.md"
  - "examples.md"
  - "changelog.md"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OfficerHalf/obsidian-jira-cloud
    - icon: fontawesome/brands/discord
      link: https://discord.gg/obsidianmd

# theme
theme:
  name: material
  logo: assets/obsidian-icon.svg
  favicon: assets/obsidian-icon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.view
    - search.suggest
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

plugins:
  - search
  - include-markdown
