name: docs-deploy
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  cancel-in-progress: true
  group: "pages"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install mkdocs-material
      
      - name: Build site
        run: mkdocs build -f doc/mkdocs.yml
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "doc/site"
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy site
        id: deploy-pages
        uses: actions/deploy-pages@v1
